version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.2
    environment:
      MEILI_ENV: development
    ports:
      - 7700:7700
    volumes:
      - ./volumes/meilisearch/:/meili_data/
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:7700/health || exit 1"]
      interval: 10s
      start_period: 30s
